#!/usr/bin/env bash
echo ('This file and process was made from https://www.915tx.com/remaster')
NAME=${1?Error: no ISO file given}
sudo apt-get install squashfs-tools genisoimage resolvconf -y -q

mkdir ~/livecdtmp

cd ~/livecdtmp

mkdir extract-cd mnt

sudo mount -o loop $NAME mnt

sudo rsync --exclude=/casper/filesystem.squashfs -a mnt/ extract-cd

sudo unsquashfs mnt/casper/filesystem.squashfs

sudo mv squashfs-root edit

sudo cp /etc/resolv.conf edit/etc/

sudo mount --bind /dev/ edit/dev

sudo chroot edit

mount -t proc none /proc && mount -t sysfs none /sys && mount -t devpts none /dev/pts

export HOME=/root && export LC_ALL=C

cd /etc/skel

mkdir Desktop Documents Downloads Music Pictures Public Templates Videos

cd /
